// server/utils/words.js

const WORD_CATEGORIES = {
  animals: [
    "cat",
    "dog",
    "fish",
    "bird",
    "frog",
    "bear",
    "deer",
    "duck",
    "cow",
    "pig",
    "lion",
    "wolf",
    "fox",
    "owl",
    "bat",
    "crab",
    "bee",
    "ant",
    "fly",
    "hen",
    "elephant",
    "penguin",
    "giraffe",
    "rabbit",
    "dolphin",
    "kangaroo",
    "flamingo",
    "octopus",
    "butterfly",
    "crocodile",
    "cheetah",
    "gorilla",
    "jellyfish",
    "turtle",
    "parrot",
    "panda",
    "koala",
    "sloth",
    "hedgehog",
    "whale",
    "seahorse",
    "starfish",
    "lobster",
    "raccoon",
    "squirrel",
    "peacock",
    "shark",
    "monkey",
    "zebra",
    "camel",
    "horse",
    "sheep",
    "goat",
    "mouse",
    "hamster",
    "lizard",
    "snail",
    "worm",
    "swan",
    "eagle",
    "toucan",
    "chameleon",
    "narwhal",
    "capybara",
    "armadillo",
    "platypus",
    "axolotl",
  ],

  food: [
    "pizza",
    "cake",
    "egg",
    "soup",
    "rice",
    "pie",
    "bread",
    "milk",
    "cheese",
    "apple",
    "banana",
    "grape",
    "lemon",
    "mango",
    "corn",
    "carrot",
    "potato",
    "tomato",
    "onion",
    "mushroom",
    "strawberry",
    "watermelon",
    "pineapple",
    "hamburger",
    "hot dog",
    "sandwich",
    "taco",
    "sushi",
    "ramen",
    "noodles",
    "pancake",
    "waffle",
    "donut",
    "ice cream",
    "cookie",
    "cupcake",
    "candy",
    "popcorn",
    "pretzel",
    "french fries",
    "nachos",
    "burrito",
    "pasta",
    "avocado",
    "broccoli",
    "bacon",
    "sausage",
    "fried egg",
    "toast",
    "smoothie",
    "lemonade",
    "coffee",
    "teapot",
    "birthday cake",
    "chocolate",
  ],

  objects: [
    "key",
    "cup",
    "hat",
    "bag",
    "box",
    "book",
    "lamp",
    "door",
    "flag",
    "bell",
    "chair",
    "table",
    "clock",
    "phone",
    "shoe",
    "sock",
    "ring",
    "crown",
    "sword",
    "shield",
    "arrow",
    "bow",
    "hammer",
    "axe",
    "rope",
    "chain",
    "umbrella",
    "backpack",
    "telescope",
    "microscope",
    "compass",
    "anchor",
    "trophy",
    "hourglass",
    "camera",
    "guitar",
    "piano",
    "drum",
    "violin",
    "bicycle",
    "skateboard",
    "basketball",
    "football",
    "baseball",
    "tennis",
    "rocket",
    "submarine",
    "helicopter",
    "parachute",
    "lighthouse",
    "castle",
    "train",
    "bus",
    "car",
    "boat",
    "plane",
    "balloon",
    "kite",
    "tent",
    "ladder",
    "bucket",
    "broom",
    "magnet",
    "battery",
    "lightbulb",
    "cactus",
    "snowman",
    "scarecrow",
    "windmill",
    "bridge",
    "well",
    "fence",
  ],

  actions: [
    "jump",
    "run",
    "swim",
    "fly",
    "sleep",
    "eat",
    "drink",
    "read",
    "write",
    "dance",
    "sing",
    "laugh",
    "cry",
    "wave",
    "clap",
    "kick",
    "throw",
    "catch",
    "climb",
    "crawl",
    "dig",
    "push",
    "pull",
    "lift",
    "carry",
    "drive",
    "cooking",
    "baking",
    "painting",
    "drawing",
    "fishing",
    "gardening",
    "skiing",
    "surfing",
    "skating",
    "rowing",
    "hiking",
    "boxing",
    "wrestling",
    "jumping rope",
    "riding a bike",
    "playing guitar",
    "playing soccer",
    "snowboarding",
    "skateboarding",
    "taking a selfie",
    "brushing teeth",
    "blowing bubbles",
    "flying a kite",
    "walking the dog",
    "washing dishes",
    "watering plants",
    "building a sandcastle",
    "roasting marshmallows",
  ],

  places: [
    "park",
    "beach",
    "farm",
    "zoo",
    "school",
    "hospital",
    "library",
    "church",
    "castle",
    "cave",
    "island",
    "desert",
    "forest",
    "jungle",
    "mountain",
    "volcano",
    "waterfall",
    "ocean",
    "river",
    "lake",
    "city",
    "village",
    "market",
    "stadium",
    "museum",
    "cinema",
    "airport",
    "train station",
    "lighthouse",
    "treehouse",
    "igloo",
    "pyramid",
    "playground",
    "aquarium",
    "carnival",
    "circus",
    "barn",
    "greenhouse",
    "space station",
    "underwater city",
    "haunted house",
    "log cabin",
    "pirate ship",
    "secret cave",
    "rooftop garden",
    "flooded street",
  ],

  movies: [
    "ghost",
    "alien",
    "robot",
    "pirate",
    "wizard",
    "ninja",
    "zombie",
    "mermaid",
    "dragon",
    "vampire",
    "werewolf",
    "superhero",
    "supervillain",
    "time machine",
    "treasure map",
    "magic carpet",
    "invisibility cloak",
    "lightsaber",
    "portal",
    "spaceship",
    "fairy tale",
    "haunted house",
    "jungle adventure",
    "underwater world",
    "carnival",
    "time travel",
    "talking animal",
    "mystery island",
    "detective",
    "spy",
    "heist",
    "giant monster",
    "shrinking potion",
    "magic mirror",
    "enchanted forest",
    "runaway train",
    "desert chase",
    "rooftop fight",
    "underwater heist",
  ],

  characters: [
    "pirate",
    "princess",
    "knight",
    "wizard",
    "chef",
    "doctor",
    "teacher",
    "astronaut",
    "firefighter",
    "police",
    "ninja",
    "superhero",
    "detective",
    "clown",
    "mime",
    "cowboy",
    "farmer",
    "sailor",
    "pilot",
    "soldier",
    "scientist",
    "painter",
    "dancer",
    "singer",
    "athlete",
    "genie",
    "fairy",
    "ghost",
    "vampire",
    "zombie",
    "robot",
    "alien",
    "mermaid",
    "skeleton",
    "monster",
    "dragon",
    "angel",
    "devil",
    "witch",
    "caveman",
    "zookeeper",
    "explorer",
    "archaeologist",
    "lifeguard",
    "referee",
  ],

  nature: [
    "sun",
    "moon",
    "star",
    "cloud",
    "rain",
    "snow",
    "wind",
    "fog",
    "ice",
    "fire",
    "wave",
    "storm",
    "thunder",
    "lightning",
    "rainbow",
    "tornado",
    "flower",
    "tree",
    "leaf",
    "grass",
    "bush",
    "vine",
    "mushroom",
    "cactus",
    "snowflake",
    "icicle",
    "puddle",
    "mud",
    "sand",
    "rock",
    "cliff",
    "sunset",
    "sunrise",
    "full moon",
    "shooting star",
    "aurora",
    "eclipse",
    "cherry blossom",
    "autumn leaves",
    "tidal wave",
    "sand dune",
    "frozen lake",
    "cracked earth",
    "blooming flower",
    "dead tree",
  ],

  vehicles: [
    "car",
    "bus",
    "van",
    "truck",
    "taxi",
    "jeep",
    "ambulance",
    "firetruck",
    "police car",
    "tractor",
    "bulldozer",
    "forklift",
    "crane",
    "tank",
    "bicycle",
    "scooter",
    "motorbike",
    "skateboard",
    "roller skates",
    "boat",
    "sailboat",
    "canoe",
    "kayak",
    "submarine",
    "yacht",
    "ferry",
    "plane",
    "jet",
    "helicopter",
    "hot air balloon",
    "rocket",
    "spaceship",
    "train",
    "subway",
    "monorail",
    "cable car",
    "gondola",
    "rickshaw",
    "horse cart",
    "dog sled",
    "hovercraft",
    "zeppelin",
  ],

  household: [
    "chair",
    "table",
    "sofa",
    "bed",
    "pillow",
    "blanket",
    "curtain",
    "window",
    "door",
    "stairs",
    "lamp",
    "clock",
    "mirror",
    "frame",
    "shelf",
    "drawer",
    "fridge",
    "oven",
    "microwave",
    "kettle",
    "toaster",
    "blender",
    "pan",
    "fork",
    "knife",
    "spoon",
    "plate",
    "bowl",
    "mug",
    "bottle",
    "jar",
    "broom",
    "mop",
    "bucket",
    "dustpan",
    "iron",
    "washing machine",
    "toilet",
    "bathtub",
    "shower",
    "sink",
    "tap",
    "toothbrush",
    "soap",
    "towel",
    "toilet paper",
    "trash can",
    "mailbox",
    "welcome mat",
  ],

  sports: [
    "football",
    "basketball",
    "tennis",
    "golf",
    "boxing",
    "swimming",
    "running",
    "cycling",
    "skiing",
    "snowboarding",
    "surfing",
    "skating",
    "volleyball",
    "baseball",
    "cricket",
    "rugby",
    "hockey",
    "archery",
    "wrestling",
    "gymnastics",
    "diving",
    "rowing",
    "sailing",
    "fencing",
    "weightlifting",
    "pole vault",
    "high jump",
    "long jump",
    "javelin",
    "table tennis",
    "badminton",
    "squash",
    "bowling",
    "darts",
    "billiards",
    "rock climbing",
    "horse riding",
    "karate",
    "judo",
    "skydiving",
  ],

  fantasy: [
    "dragon",
    "unicorn",
    "phoenix",
    "griffin",
    "mermaid",
    "centaur",
    "werewolf",
    "vampire",
    "wizard",
    "witch",
    "goblin",
    "troll",
    "elf",
    "dwarf",
    "fairy",
    "genie",
    "giant",
    "cyclops",
    "hydra",
    "kraken",
    "magic wand",
    "spell book",
    "crystal ball",
    "magic potion",
    "treasure",
    "enchanted sword",
    "flying carpet",
    "golden egg",
    "magic mirror",
    "invisible cloak",
    "dragon egg",
    "fairy dust",
    "enchanted forest",
    "cursed castle",
    "sunken ship",
    "forbidden tower",
    "mystic portal",
  ],
};

const WORDS = Object.values(WORD_CATEGORIES).flat();

const getRandomWord = (category = "all", customWords = []) => {
  if (customWords && customWords.length > 0) {
    return customWords[Math.floor(Math.random() * customWords.length)];
  }
  const pool = category === "all" ? WORDS : WORD_CATEGORIES[category] || WORDS;
  return pool[Math.floor(Math.random() * pool.length)];
};

const getThreeChoices = (category = "all", customWords = []) => {
  const pool =
    customWords && customWords.length > 0
      ? customWords
      : category === "all"
        ? WORDS
        : WORD_CATEGORIES[category] || WORDS;
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return [...new Set(shuffled)].slice(0, 3);
};

const getWordChoices = () => getThreeChoices();

// Multi-word hints: each word's letters shown as underscores separated by spaces.
// Words are separated from each other by THREE spaces so players can see
// how many words there are without any special character.
// e.g. "magic wand"  → "_ _ _ _ _   _ _ _ _"
// e.g. "elephant"    → "_ _ _ _ _ _ _ _"
const getWordHint = (word, revealedIndices = new Set()) => {
  const words = word.split(" ");

  if (words.length === 1) {
    return word
      .split("")
      .map((char, i) => (revealedIndices.has(i) ? char : "_"))
      .join(" ");
  }

  let charIndex = 0;
  const wordHints = words.map((w) => {
    const hint = w
      .split("")
      .map((char, j) => (revealedIndices.has(charIndex + j) ? char : "_"))
      .join(" ");
    charIndex += w.length + 1;
    return hint;
  });

  return wordHints.join("   ");
};

const checkGuess = (guess, word) =>
  guess.trim().toLowerCase() === word.trim().toLowerCase();

const editDistance = (a, b) => {
  a = a.toLowerCase().trim();
  b = b.toLowerCase().trim();
  const dp = Array.from({ length: a.length + 1 }, (_, i) =>
    Array.from({ length: b.length + 1 }, (_, j) =>
      i === 0 ? j : j === 0 ? i : 0,
    ),
  );
  for (let i = 1; i <= a.length; i++) {
    for (let j = 1; j <= b.length; j++) {
      dp[i][j] =
        a[i - 1] === b[j - 1]
          ? dp[i - 1][j - 1]
          : 1 + Math.min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1]);
    }
  }
  return dp[a.length][b.length];
};

const getLetterFeedback = (guess, word) => {
  guess = guess.toLowerCase().trim();
  word = word.toLowerCase().trim();
  const result = Array(guess.length).fill("absent");
  const wordChars = word.split("");
  const used = Array(word.length).fill(false);
  for (let i = 0; i < guess.length; i++) {
    if (guess[i] === wordChars[i]) {
      result[i] = "correct";
      used[i] = true;
    }
  }
  for (let i = 0; i < guess.length; i++) {
    if (result[i] === "correct") continue;
    for (let j = 0; j < wordChars.length; j++) {
      if (!used[j] && guess[i] === wordChars[j]) {
        result[i] = "present";
        used[j] = true;
        break;
      }
    }
  }
  return result;
};

const getNextRevealIndex = (word, revealedIndices) => {
  const candidates = [];
  for (let i = 0; i < word.length; i++) {
    if (word[i] !== " " && !revealedIndices.has(i)) candidates.push(i);
  }
  if (candidates.length === 0) return null;
  return candidates[Math.floor(Math.random() * candidates.length)];
};

module.exports = {
  WORDS,
  WORD_CATEGORIES,
  getRandomWord,
  getThreeChoices,
  getWordChoices,
  getWordHint,
  checkGuess,
  editDistance,
  getLetterFeedback,
  getNextRevealIndex,
};
